openai_api_key: "<your-api-key"

retrieval_classifier:
  prompt_template: |
    Given Query and chatgpt response, answer Yes if the response was a valid answer and No if the response was unable to answer the user's questions due to chatgpt limitations
    
    Examples 1
    Query: what is the financial outlook for 2024
    Response: I'm sorry, but I don't have real-time information as my training only includes data up to January 2022, and I don't have browsing capabilities. Predicting the financial outlook for a specific year involves considering various factors, such as economic indicators, geopolitical events, and global trends, which can change rapidly.
    Answer: No
  
    Example 2
    Query: who is the ceo of twitter
    Response: Jack Dorsey was the CEO of Twitter. 
    Answer: Yes
    
    Query: {}
    Response: {}
    Answer:
